collections:
  - name: "testRecords"
    singular: "testRecord"
    plural: "testRecords"
    properties:
      - name: "thisIsPlainText"
        type: "plainText"
      
      - name: "thisIsRichText"
        type: "richText"

      - name: "thisIsEmail"
        type: "email"

      - name: "thisIsUrl"
        type: "url"
      
      - name: "thisIsNumber"
        type: "number"
      
      - name: "thisIsSingleRelation"
        type: "relation"
        to: "testRecords"
        mode: "single"
        
      - name: "thisIsMultipleRelation"
        type: "relation"
        to: "testRecords"
        mode: "multiple"
      
      - name: "thisIsDateTime"
        type: "datetime"
      
      - name: "thisIsBoolean"
        type: "boolean"
      
      - name: "thisIsJson"
        type: "json"

      - name: "thisIsSingleSelect"
        type: "select"
        mode: "single"
        options:
          - "somebody"
          - "once"
          - "told"
          - "me"
      
      - name: "thisIsMultipleSelect"
        type: "select"
        mode: "multiple"
        options:
          - "the"
          - "world"
          - "is"
          - "gonna"
          - "roll"
          - "me"
        
      - name: "thisIsSingleFile"
        type: "file"
        mode: "single"
        
      - name: "thisIsMultipleFile"
        type: "file"
        mode: "multiple"

      - name: "thisIsAutoDate"
        type: "autoDatetime"

      - name: "thisIsGeoPoint"
        type: "geoPoint"
